[package]
name = "day-2"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "part-1"
path = "src/part-1.rs"

[[bin]]
name = "part-2"
path = "src/part-2.rs"

[dependencies]
common = { path = "../common" }