[package]
name = "scripts"
version = "0.1.0"
edition = "2021"

[dependencies]
toml = "0.4.2"
regex = "1"
serde = "1.0.147"
serde_derive = "1.0.147"
common = { path = "../common" }

[[bin]]
name = "generate"
path = "src/generate.rs"
